### PR TITLE
Per dimension storage frequency

### PR DESCRIPTION
**Pull request by igentuman**
Added new config option and a logic

### CODE REVIEW

**Comment by covers1624** [comment]
1.12 is not supported.

This is also a feature I'm not interested in adding.

**Comment by igentuman** [comment]
@covers1624 i was wondering if i can request permission to maintain 1.12 version on cursedforge as separate mod? i need that for my modpack
with all the credits ofcource

**Comment by covers1624** [comment]
You shouldn't need perms for this, feel free to create a modified version and ship it with your modpack. If curse complain, show them this issue :)

**Comment by Ecu** [comment]
Yeah.  Ender Storage is under the MIT license.  So, as long as you follow that, you're fine.  Which is basically a non-issue to do.

**Pull request closed without merging**
